version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - whisper-socket:/app/sockets
      - llama-socket:/app/llama-sockets
      - piper-socket:/app/piper-sockets
    ports:
      - "8090:8090"
    depends_on:
      whisper:
        condition: service_healthy
      llama:
        condition: service_started
      piper:
        condition: service_healthy
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for whisper socket…' &&
      while [ ! -S /app/sockets/whisper.sock ]; do sleep 0.2; done &&
      echo 'Waiting for llama socket…' &&
      while [ ! -S /app/llama-sockets/llama.sock ]; do sleep 0.2; done &&
      echo 'Waiting for piper socket…' &&
      while [ ! -S /app/piper-sockets/piper.sock ]; do sleep 0.2; done &&
      echo 'All backends ready; starting API…' &&
      exec /app/server"

  whisper:
    build:
      context: .
      dockerfile: whisper/Dockerfile
      args: [CUDA_ARCHS=89]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - WHISPER_MODEL=kb-ggml-model.bin
    volumes:
      - whisper-socket:/app/sockets
    ulimits:
      memlock: -1          # allow page-locked (“pinned”) memory
      stack:   67108864    # 64 MiB stack – CUDA’s usual default
    healthcheck:
      test: ["CMD", "test", "-S", "/app/sockets/whisper.sock"]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 10s
    restart: on-failure

  llama:
    build:
      context: .
      dockerfile: llama_server/Dockerfile
      args: [CUDA_ARCHS=89]
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      LLAMA_N_CTX: 2048
      LLAMA_N_GPU_LAYERS: 32      # 32 layers in the model → 32 to GPU
      GGML_CUDA_FORCE_MMQ: "1"
    volumes:
      - llama-socket:/app/llama-sockets
      - ./llama_models:/app/models
    ulimits:
      memlock: -1
      stack:   67108864
    healthcheck:
      test: ["CMD", "test", "-S", "/app/llama-sockets/llama.sock"]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 10s
    restart: on-failure

  piper:
    build:
      context: .
      dockerfile: piper_server/Dockerfile
      args: [CUDA_ARCHS=89]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - piper-socket:/app/piper-sockets
      - ./piper_models:/app/models
    ulimits:
      memlock: -1
      stack:   67108864
    healthcheck:
      test: ["CMD", "test", "-S", "/app/piper-sockets/piper.sock"]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 10s
    restart: on-failure

volumes:
  whisper-socket:
  llama-socket:
  piper-socket:
  whisper-models: