version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - whisper-socket:/app/sockets
    depends_on:
      whisper:
        condition: service_healthy
    restart: on-failure
    # Modify your API service to initially wait for the whisper service
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for whisper service to be ready...' &&
      while [ ! -f /app/sockets/ready ]; do sleep 0.5; done &&
      echo 'Whisper service is ready, starting API...' &&
      exec /app/api"

  whisper:
    build:
      context: .
      dockerfile: whisper/Dockerfile
    volumes:
      - whisper-socket:/app/sockets
      - whisper-models:/app/models
    environment:
      - WHISPER_MODEL=ggml-base.en.bin
      # Force CPU mode to avoid GPU-related crashes
      - WHISPER_USE_GPU=0
    healthcheck:
      test: ["CMD", "test", "-f", "/app/sockets/ready"]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 10s
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 5G

volumes:
  whisper-socket:
    driver: local
  whisper-models:
    driver: local